<a href="https://colab.research.google.com/github/BakaPika/PCS221_Cloud-Infrastructure-and-Services/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1

In [ ]:
import numpy as np
import pandas as pd

rows = 20_000        # total rows
cols = 10_000        # total columns
chunk_size = 500     # rows per chunk (safe for memory)

npy_file = "big_data.npy"
csv_sample_file = "sample_data.csv"

data = np.memmap(
    npy_file,
    dtype=np.float32,
    mode="w+",
    shape=(rows, cols)
)

for start in range(0, rows, chunk_size):
    end = min(start + chunk_size, rows)


    block = np.zeros((end - start, cols), dtype=np.float32)


    block[:, :3334] = np.random.uniform(
        0, 1, size=(end - start, 3334)
    )


    block[:, 3334:6667] = np.random.normal(
        0, 1, size=(end - start, 3333)
    )


    block[:, 6667:] = np.random.randint(
        0, 100, size=(end - start, cols - 6667)
    )


    data[start:end] = block

    print(f"Saved rows {start} to {end}")


data.flush()
print("Finished creating big_data.npy")


sample_rows = 100
sample_cols = 50

sample = data[:sample_rows, :sample_cols]

df = pd.DataFrame(sample)
df.to_csv(csv_sample_file, index=False)

print(f"CSV sample saved as {csv_sample_file}")


Saved rows 0 to 500
Saved rows 500 to 1000
Saved rows 1000 to 1500
Saved rows 1500 to 2000
Saved rows 2000 to 2500
Saved rows 2500 to 3000
Saved rows 3000 to 3500
Saved rows 3500 to 4000
Saved rows 4000 to 4500
Saved rows 4500 to 5000
Saved rows 5000 to 5500
Saved rows 5500 to 6000
Saved rows 6000 to 6500
Saved rows 6500 to 7000
Saved rows 7000 to 7500
Saved rows 7500 to 8000
Saved rows 8000 to 8500
Saved rows 8500 to 9000
Saved rows 9000 to 9500
Saved rows 9500 to 10000
Saved rows 10000 to 10500
Saved rows 10500 to 11000
Saved rows 11000 to 11500
Saved rows 11500 to 12000
Saved rows 12000 to 12500
Saved rows 12500 to 13000
Saved rows 13000 to 13500
Saved rows 13500 to 14000
Saved rows 14000 to 14500
Saved rows 14500 to 15000
Saved rows 15000 to 15500
Saved rows 15500 to 16000
Saved rows 16000 to 16500
Saved rows 16500 to 17000
Saved rows 17000 to 17500
Saved rows 17500 to 18000
Saved rows 18000 to 18500
Saved rows 18500 to 19000
Saved rows 19000 to 19500
Saved rows 19500 to 20000
Fini

Q2

In [ ]:
import numpy as np


A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

first_row = A[0]


A[1:] = A[1:] + first_row

print("Resulting Matrix:")
print(A)


Resulting Matrix:
[[ 1  2  3]
 [ 5  7  9]
 [ 8 10 12]]


In [ ]:
A = np.loadtxt("sample_data.csv", delimiter=",", skiprows=1)
print("---Original CSV data---")
print(A)

first_row = A[0]
A[1:] = A[1:] + first_row

print(" ")
print("---Updated CSV data---")
print(A)

---Original CSV data---
[[0.4345201  0.6911194  0.6011785  ... 0.37035814 0.36190307 0.05834458]
 [0.4541947  0.8402622  0.9897637  ... 0.80121344 0.82433224 0.6399883 ]
 [0.05358237 0.02488247 0.20448865 ... 0.02944355 0.45669046 0.49530196]
 ...
 [0.93630266 0.43919906 0.5433817  ... 0.41626737 0.72472936 0.4309564 ]
 [0.29424602 0.19044931 0.83757484 ... 0.71504825 0.45326737 0.48757565]
 [0.9056127  0.43530607 0.16286793 ... 0.88823116 0.36122093 0.35918966]]
 
---Updated CSV data---
[[0.4345201  0.6911194  0.6011785  ... 0.37035814 0.36190307 0.05834458]
 [0.8887148  1.5313816  1.5909422  ... 1.17157158 1.18623531 0.69833288]
 [0.48810247 0.71600187 0.80566715 ... 0.39980169 0.81859353 0.55364654]
 ...
 [1.37082276 1.13031846 1.1445602  ... 0.78662551 1.08663243 0.48930098]
 [0.72876612 0.88156871 1.43875334 ... 1.08540639 0.81517044 0.54592023]
 [1.3401328  1.12642547 0.76404643 ... 1.2585893  0.723124   0.41753424]]


Q3

In [1]:
import numpy as np
from collections import defaultdict

arr = np.array([1, 2, 2, 3, 1, 4, 3, 2])

groups = defaultdict(list)

for val in arr:
    groups[val].append(val)


grouped_matrix = np.array(list(groups.values()), dtype=object)

print("Grouped Matrix:")
print(grouped_matrix)


Grouped Matrix:
[list([np.int64(1), np.int64(1)])
 list([np.int64(2), np.int64(2), np.int64(2)])
 list([np.int64(3), np.int64(3)]) list([np.int64(4)])]


Q4

In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(A+B)
print()
print(A-B)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import random
n = random.randint(1, 10)
A = np.random.randint(1, 20, size=(n, n))*2
A

array([[ 6, 18, 22, 26, 30, 26],
       [ 8, 36,  6, 38, 10, 28],
       [26, 16, 36,  4, 22, 14],
       [22, 28,  4, 34, 28, 30],
       [18, 10, 36, 38, 30, 38],
       [14, 10, 22, 14, 26, 28]])

In [ ]:
A = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

row_sums = tuple(sum(row) for row in A)
print(row_sums)


(6, 15, 24)
